#!/bin/sh -e
# Based on the Debian wrapper script written by Jens Reyer and Michael Gilbert
# SPDX-License-Identifier: LGPL-2.1-or-later

wineserver32=/usr/libexec/wine/wineserver32
wineserver64=/usr/libexec/wine/wineserver64

# Determine the parent process architecture
arch=$(file -L /proc/$PPID/exe | grep -o 'ELF 32-bit\|ELF 64-bit')

if test "$arch" = "ELF 32-bit"; then
     if test -x "$wineserver32"; then
         wineserver=$wineserver32
     else
	 echo "error: unable to find 32bit wineserver executable." >&2
	 exit 1
     fi
elif test "$arch" = "ELF 64-bit"; then
     if test -x "$wineserver64"; then
         wineserver=$wineserver64
     else
	 echo "error: unable to find 64bit wineserver executable." >&2
	 exit 1
     fi
else
    echo "error: unable to determine architecture." >&2
    exit 1
fi

exec $wineserver -p0 "$@"
